name = "Demagnetize"
filename = "demagnetize-1.12.2-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2834/566/demagnetize-1.12.2-1.1.1.jar"
hash-format = "murmur2"
hash = "2953308073"

[update]
[update.curseforge]
file-id = 2834566
project-id = 301356
release-channel = "beta"
